### ISSUE TITLE
Say hi~~ 

### ISSUE THREAD

**Issue by wave2588** [OstrichRunning/GestureView#1]
Hi~~ 您好哈, 看到您写的demo和我想要的效果十分相似,  不知是否可以添加一个初始值的旋转角度?

**Comment by OstrichRunning** [comment]
hi：
   初始化旋转是在创建子视图时设定，由于形变是叠加的，所以你只需要关心你创建的子视图即可 你可以看vc里的测试（代码已提交）
best wishes.

**Comment by wave2588** [comment]
我发现 CRGestureView 在 addSubview 时, 如果没有实现 CRGestureActionViewProtocol 协议的 View 是不允许添加的, 请问是为什么呢? 是否方便加个 QQ or 微信 细聊下呢?
qq: 787138980
wechat: zzbbc2588

**Comment by OstrichRunning** [comment]
CRGestureView 作为实现手势的视图 期望子视图都是满足特点特征 这样方便 针对特征来管理 不然就会在管理时进行判断。
这里最主要还是希望CRGestureView功能集中，尽量少而其他扩展功能都由子视图自定义实现 减少为了实现功能而对CRGestureView的修改
